require 'geoservices/base'
require 'geoservices/layerable'
require 'geoservices/queryable'
require 'geoservices/service/catalog'
require 'geoservices/service/feature_service'
require 'geoservices/service/map_service'
